Carthage support
TakeScoop/SwiftyButton pull request #8
Opened 2016-12-24 20:40 UTC by RemyDCF

2017-01-03 18:34 UTC, ldiqual commented
@RemyDCF Thanks a lot for this! Can you describe what you actually did here?

2017-01-03 20:25 UTC, RemyDCF commented
I marked the SwiftyButton scheme as shared for adding the Carthage support (as described at https://github.com/Carthage/Carthage). I also updated the README.md.

2017-01-06 04:52 UTC, ldiqual requested changes
@RemyDCF Awesome, thanks for the explanations. Just one minor fix and it'll be good to go. Can you also add something in the changelog? Thank you

2017-01-06 04:52 UTC, ldiqual commented on README.md
> +SwiftyButton
Can you discard those changes, it clutter the diff a bit

2017-01-06 12:34 UTC, RemyDCF commented
Which version number I add to the Changelog ?

2017-01-06 12:35 UTC, RemyDCF commented on README.md
> +SwiftyButton
Done

2017-01-06 21:10 UTC, ldiqual commented
@RemyDCF Add it in the `master` section.

2017-01-06 21:23 UTC, RemyDCF commented
Done

2017-01-06 21:34 UTC, ldiqual requested changes

2017-01-06 21:34 UTC, ldiqual commented on CHANGELOG.md
> + - Adding Carthage support.
This is in the `0.6.0` section, not the master section.

2017-01-06 21:36 UTC, RemyDCF commented on CHANGELOG.md
> + - Adding Carthage support.
Ok, I changed this.

2017-01-06 21:37 UTC, ldiqual commented
Perfect, thank you so much for your contribution!

2017-01-06 21:37 UTC, merged